### ISSUE TITLE
Waiting for socket connections on port 11411 waiting for socket connection

### ISSUE THREAD

**Issue by Shihab-Haque** [adamkrawczyk/esp32_rosserial_demo#4]
Hi ! I have followed the tutorial and did everything according to it, but after running: 

rosrun rosserial_python serial_node.py tcp 11411

it stays stuck on :  Waiting for socket connections on port 11411
waiting for socket connection

I can't seem to find out where the error is, can you please guide me? thanks in advance.

**Comment by Shihab-Haque** [comment]
The issue has been solved , thank you so much for this awesome repo.

**Comment by shreyassule7738** [comment]
Can you please elaborate how you solved the issue?

**Comment by adamkrawczyk** [comment]
hi, I need to recap. wondering why this solved was not posted here. 

I will go back here when I got some free time (possibly tomorrow)

**Comment by adamkrawczyk** [comment]
@Shihab-Haque Do you remember what was the solution?
